apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-kubeconfig
  namespace: spire

---

# Required cluster role to allow spire-agent to query k8s API server
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get"]

---

# Binds above cluster role to spire-agent service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-agent-tokenreview-binding
subjects:
- kind: ServiceAccount
  name: spire-kubeconfig
  namespace: spire
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io

---
# Binds above cluster role to spire-agent service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-agent-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: spire-kubeconfig
  namespace: spire
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Secret
metadata:
  name: agent-sa-secret
  namespace: spire
  annotations:
    kubernetes.io/service-account.name: spire-kubeconfig
type: kubernetes.io/service-account-token

---
